# Generated by Django 2.2.2 on 2019-07-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
