# Generated by Django 2.2.2 on 2019-07-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20190703_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
