# Generated by Django 2.2.2 on 2019-07-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20190701_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='contatos',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Convite',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
