# Generated by Django 2.2.2 on 2019-07-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='avatar/default_avatar.png', upload_to='avatar'),
        ),
    ]
