# Generated by Django 2.2.2 on 2019-07-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190703_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friendship',
            field=models.ManyToManyField(to='authentication.User'),
        ),
    ]
